/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as MainLayoutRouteImport } from './app/_main/layout'
import { Route as MainIndexRouteImport } from './app/_main/index'
import { Route as MainQuestRouteImport } from './app/_main/quest'
import { Route as MainLoginRouteImport } from './app/_main/login'
import { Route as MainLetterRouteImport } from './app/_main/letter'
import { Route as MainGalleryRouteImport } from './app/_main/gallery'
import { Route as MainQuestTicTacToeRouteImport } from './app/_main/quest_.tic-tac-toe'
import { Route as MainQuestAnticipationRouteImport } from './app/_main/quest_.anticipation'

const MainLayoutRoute = MainLayoutRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainQuestRoute = MainQuestRouteImport.update({
  id: '/quest',
  path: '/quest',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLoginRoute = MainLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLetterRoute = MainLetterRouteImport.update({
  id: '/letter',
  path: '/letter',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainGalleryRoute = MainGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainQuestTicTacToeRoute = MainQuestTicTacToeRouteImport.update({
  id: '/quest_/tic-tac-toe',
  path: '/quest/tic-tac-toe',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainQuestAnticipationRoute = MainQuestAnticipationRouteImport.update({
  id: '/quest_/anticipation',
  path: '/quest/anticipation',
  getParentRoute: () => MainLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/gallery': typeof MainGalleryRoute
  '/letter': typeof MainLetterRoute
  '/login': typeof MainLoginRoute
  '/quest': typeof MainQuestRoute
  '/quest/anticipation': typeof MainQuestAnticipationRoute
  '/quest/tic-tac-toe': typeof MainQuestTicTacToeRoute
}
export interface FileRoutesByTo {
  '/gallery': typeof MainGalleryRoute
  '/letter': typeof MainLetterRoute
  '/login': typeof MainLoginRoute
  '/quest': typeof MainQuestRoute
  '/': typeof MainIndexRoute
  '/quest/anticipation': typeof MainQuestAnticipationRoute
  '/quest/tic-tac-toe': typeof MainQuestTicTacToeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainLayoutRouteWithChildren
  '/_main/gallery': typeof MainGalleryRoute
  '/_main/letter': typeof MainLetterRoute
  '/_main/login': typeof MainLoginRoute
  '/_main/quest': typeof MainQuestRoute
  '/_main/': typeof MainIndexRoute
  '/_main/quest_/anticipation': typeof MainQuestAnticipationRoute
  '/_main/quest_/tic-tac-toe': typeof MainQuestTicTacToeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/letter'
    | '/login'
    | '/quest'
    | '/quest/anticipation'
    | '/quest/tic-tac-toe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/gallery'
    | '/letter'
    | '/login'
    | '/quest'
    | '/'
    | '/quest/anticipation'
    | '/quest/tic-tac-toe'
  id:
    | '__root__'
    | '/_main'
    | '/_main/gallery'
    | '/_main/letter'
    | '/_main/login'
    | '/_main/quest'
    | '/_main/'
    | '/_main/quest_/anticipation'
    | '/_main/quest_/tic-tac-toe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main/quest': {
      id: '/_main/quest'
      path: '/quest'
      fullPath: '/quest'
      preLoaderRoute: typeof MainQuestRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main/login': {
      id: '/_main/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MainLoginRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main/letter': {
      id: '/_main/letter'
      path: '/letter'
      fullPath: '/letter'
      preLoaderRoute: typeof MainLetterRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main/gallery': {
      id: '/_main/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof MainGalleryRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main/quest_/tic-tac-toe': {
      id: '/_main/quest_/tic-tac-toe'
      path: '/quest/tic-tac-toe'
      fullPath: '/quest/tic-tac-toe'
      preLoaderRoute: typeof MainQuestTicTacToeRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main/quest_/anticipation': {
      id: '/_main/quest_/anticipation'
      path: '/quest/anticipation'
      fullPath: '/quest/anticipation'
      preLoaderRoute: typeof MainQuestAnticipationRouteImport
      parentRoute: typeof MainLayoutRoute
    }
  }
}

interface MainLayoutRouteChildren {
  MainGalleryRoute: typeof MainGalleryRoute
  MainLetterRoute: typeof MainLetterRoute
  MainLoginRoute: typeof MainLoginRoute
  MainQuestRoute: typeof MainQuestRoute
  MainIndexRoute: typeof MainIndexRoute
  MainQuestAnticipationRoute: typeof MainQuestAnticipationRoute
  MainQuestTicTacToeRoute: typeof MainQuestTicTacToeRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainGalleryRoute: MainGalleryRoute,
  MainLetterRoute: MainLetterRoute,
  MainLoginRoute: MainLoginRoute,
  MainQuestRoute: MainQuestRoute,
  MainIndexRoute: MainIndexRoute,
  MainQuestAnticipationRoute: MainQuestAnticipationRoute,
  MainQuestTicTacToeRoute: MainQuestTicTacToeRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainLayoutRoute: MainLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
